Repository 4-2-mogazoa/mogazoa, pull requests merged in 2024-03, with the labels that each got.

#9 chore: eslint 플러그인 설치 및 설정
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#30 feat: 프로필 이미지 컴포넌트 구현
  .storybook/main.ts
  public/images/testImage.png
  src/components/common/profileImage/ProfileImage.tsx
  src/stories/ProfileImage.stories.ts
  src/styles/globals.css
  src/utils/cn.ts
Labels: 🎨 Style

#24 style: 기본 버튼 공통 컴포넌트 구현
  .storybook/preview.ts
  src/components/common/button/BasicButton.tsx
  src/components/test
  src/stories/BasicButton.stories.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 Style

#29 feat: 카테고리 뱃지 컴포넌트 구현
  src/components/common/categoryBadge/CategoryBadge.tsx
  src/stories/CategoryBadge.stories.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 Style

#35 feat:카테고리 필터 버튼 컴포넌트 구현
  src/components/common/categoryFilterButton/CategoryFilter.tsx
  src/stories/CategoryFilterButton.stories.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 Style

#32 feat: 랭킹 컴포넌트 구현
  src/components/common/ranking/Ranking.tsx
  src/stories/Ranking.stories.ts
  src/styles/globals.css
Labels: 🎨 Style

#50 chore: css black 색상 지정
  src/components/common/categoryFilterButton/CategoryFilter.tsx
  tailwind.config.ts
Labels: 🎨 Style

#42 feat: 카드 컴포넌트(Activity) 구현
  src/components/common/activitycard/ActivityCard.tsx
  src/stories/ActivityCard.stories.ts
Labels: 🎨 Style

#46 feat: 카드 컴포넌트(Product) 구현
  public/images/supersonic.svg
  src/components/common/productcard/ProductCard.tsx
  src/stories/ProductCard.stories.ts
Labels: 🎨 Style

#34 feat:메뉴공통컴포넌트
  public/icons/hamburger.svg
  public/icons/logo.svg
  src/components/common/menu/Header.tsx
  src/components/common/menu/SideBar.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.tsx
  src/stories/SideBar.stories.ts
  src/stories/header.css
  src/utils/test
Labels: 🎨 Style

#40 Faet/인풋 공통 컴포넌트작업
  .gitignore
  src/components/common/inputs/AddImageBox.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/inputs/TextBox.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/formtest/index.tsx
  src/stories/AddImageBox.stories.ts
  src/stories/Input.stories.ts
  src/stories/Page.stories.ts
  src/stories/TextBox.stories.ts
  src/utils/cn.ts
Labels: 🎨 Style

#48 Feat: 드랍다운 컴포넌트 구현
  src/components/common/button/BasicButton.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/DropdownFilterInput.tsx
  src/components/common/dropdown/DropdownList.tsx
  src/components/common/dropdown/DropdownToggleButton.tsx
  src/hooks/common/useOutsideClick.ts
  src/stories/Dropdown.stories.tsx
  src/types/common.ts
Labels: 🎨 Style

#66 setting: zustand 설치
  package-lock.json
  package.json
Labels: ⚙ Setting

#67 fix: 반응형 구현 및 프롭 수정
  src/components/common/menu/SideBar.tsx
  src/stories/SideBar.stories.ts
  src/types/common.ts
Labels: 🎨 Style

#70 style: 드롭다운 스타일 변경
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/DropdownList.tsx
  src/components/common/dropdown/DropdownToggleButton.tsx
Labels: 🎨 Style

#74 chore: 프로필 기본 이미지 설정
  src/components/common/followerProfile/FollowerProfile.tsx
  src/components/common/profileImage/ProfileImage.tsx
  src/components/common/reviewerProfile/ReviewerProfile.tsx
  src/stories/FollowerProfile.stories.ts
  src/stories/ReviewerProfile.stories.ts
Labels: 🎨 Style

#78 fix/ProductCard 컴포넌트 수정
  src/components/common/productcard/ProductCard.tsx
Labels: 😈 BugFix

#80 Feat/ TanStackQuery Provider 및 공통스타일 헤더추가
  src/pages/_app.tsx
Labels: ⚙ Setting

#75 Feat/로그인 레이아웃 개발
  src/components/auth/AuthContainer.tsx
  src/components/auth/OAuthLayout.tsx
  src/components/auth/form/AuthFormContainer.tsx
  src/components/auth/form/SignInForm.tsx
  src/components/common/inputs/Input.tsx
  src/constants/regExp.tsx
  src/constants/test
  src/pages/signin/index.tsx
  src/stories/AuthContainer.stories.ts
  src/stories/OAuthLayout.stories.ts
  src/stories/SignInForm.stories.ts
  src/stories/SingInPage.stories.ts
Labels: 🎨 Style

#81 Feat/회원가입 레이아웃 개발
  src/components/auth/AuthContainer.tsx
  src/components/auth/form/SignupForm.tsx
  src/components/common/auth/AuthContainer.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/productcard/ProductCard.tsx
  src/constants/regExp.tsx
  src/pages/_app.tsx
  src/pages/signup/index.tsx
Labels: 🎨 Style

#95 feat:프로필 페이지 UI
  next.config.mjs
  src/components/common/activitycard/ActivityCard.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/DropdownFilterInput.tsx
  src/components/common/dropdown/DropdownList.tsx
  src/components/common/dropdown/DropdownToggleButton.tsx
  src/components/common/productcard/ProductCard.tsx
  src/components/profile/ActivityDetails.tsx
  src/components/profile/FilteredProductList.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ProfilePageLayout.tsx
  src/constants/breakPoint.ts
  src/hooks/common/useThrottle.ts
  src/hooks/common/useWindowWidth.ts
  src/pages/profile/[id].tsx
  src/pages/profile/my.tsx
  src/types/common.ts
  src/types/test
  src/types/user.ts
Labels: 🎨 Style

#92 feat: DetailCard 컴포넌트 UI 구현
  public/images/headset.svg
  src/components/productdetail/DetailCard.tsx
  src/stories/DetailCard.stories.ts
  src/types/common.ts
  src/types/product.ts
Labels: 🎨 Style

#104 feat: axios instance 함수 구현
  src/apis/axiosInstance.ts
  src/utils/getCookies.ts
Labels: 💡Feature

#99 feat: ReviewCard 컴포넌트 UI 구현
  public/icons/star_off.svg
  public/icons/star_on.svg
  public/images/profile1.svg
  public/images/test1.jpg
  public/images/test2.png
  src/components/productdetail/ReviewCard.tsx
  src/stories/ReviewCard.stories.ts
  src/types/product.ts
Labels: 🎨 Style

#103 style: 상품 추가 버튼
  src/components/common/button/AddProductButton.tsx
Labels: 🎨 Style

#118 Fix/회원가입 기능구현 일부수정
  src/apis/postSignup.ts
  src/components/auth/AuthContainer.tsx
Labels: 😈 BugFix

#110 feat: 상품상세화면 페이지UI 구현
  public/icons/none_review.svg
  src/components/common/activitycard/ActivityCard.tsx
  src/components/common/productcard/ProductCard.tsx
  src/components/common/statisticscard/StatisticsCard.tsx
  src/components/productdetail/DetailCard.tsx
  src/components/productdetail/MockData.ts
  src/components/productdetail/ProductDetail.tsx
  src/components/productdetail/ProductDetailPageLayout.tsx
  src/components/productdetail/ProductReview.tsx
  src/components/productdetail/ProductStatistics.tsx
  src/components/productdetail/ReviewCard.tsx
  src/constants/filterBy.ts
  src/pages/productdetail/[id].tsx
  src/stories/DetailCard.stories.ts
  src/stories/ProductDetailPageLayout.stories.ts
  src/types/product.ts
Labels: 🎨 Style

#106 Feat: 비교상품상태관리
  src/apis/products.ts
  src/components/compare/CompareForm.tsx
  src/components/compare/CompareInput.tsx
  src/hooks/compare/useCompareInputState.ts
  src/hooks/compare/useCompareQueries.ts
  src/pages/compare/index.tsx
  src/store/compare.ts
  src/types/common.ts
  src/types/product.ts
Labels: 💡Feature, 🎨 Style

#112 feat: 모달 상태 전역 관리 등
  src/components/common/inputs/TextBox.tsx
  src/components/common/modal/ModalWrapper.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/ProfileModifyModal.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/store/modal.ts
Labels: 💡Feature

#122 Feat/로그인 기능구현
  src/apis/auth/postSignin.ts
  src/apis/auth/postSignup.ts
  src/components/auth/form/SignInForm.tsx
  src/components/auth/form/SignupForm.tsx
Labels: 💡Feature

#123 Feat: 비교 결과 UI
  src/apis/products.ts
  src/components/compare/CompareForm.tsx
  src/components/compare/CompareInput.tsx
  src/components/compare/EachResult.tsx
  src/components/compare/EachResultImage.tsx
  src/components/compare/EachResultLayout.tsx
  src/components/compare/EachResultLink.tsx
  src/components/compare/EachResultTitle.tsx
  src/components/compare/FinalResultDescription.tsx
  src/components/compare/Result.tsx
  src/pages/compare/index.tsx
  src/styles/globals.css
  src/types/compare.ts
  src/utils/compare.ts
Labels: 🎨 Style

#124 feat: 유저가/를 팔로우 하는 유저 목록 모달
  src/apis/user.ts
  src/components/profile/FollowUsersModal.tsx
  src/components/profile/ProfileCard.tsx
  src/pages/_app.tsx
  src/types/user.ts
Labels: 💡Feature

#127 Feat: 비교하기 폼 기능 (무한스크롤 등) 구현 및 수정
  public/icons/loading.svg
  src/components/common/productNameTag/ProductNameTag.tsx
  src/components/compare/CompareDropdown.tsx
  src/components/compare/CompareForm.tsx
  src/components/compare/CompareInput.tsx
  src/components/compare/EachResult.tsx
  src/components/compare/EachResultTitle.tsx
  src/components/compare/Loading.tsx
  src/hooks/compare/useCompareInputState.ts
  src/hooks/compare/useCompareQueries.ts
  src/pages/compare/index.tsx
  src/pages/compare/scrollTest.tsx
  src/store/compare.ts
  src/styles/globals.css
  src/utils/getDataByScroll.ts
Labels: 💡Feature, 🎨 Style

#129 Feat: 비교하기 모달 구현
  src/components/compare/ChangeProductModal.tsx
  src/components/compare/MovingPageModal.tsx
  src/hooks/compare/useCompareModal.tsx
  src/pages/compare/testModal.tsx
  src/store/compare.ts
  src/types/compare.ts
Labels: 💡Feature, 🎨 Style

#134 feat: 유저 페이지 기능
  src/apis/follow.ts
  src/apis/user.ts
  src/components/common/activitycard/ActivityCard.tsx
  src/components/common/inputs/TextBox.tsx
  src/components/common/productcard/ProductCard.tsx
  src/components/common/profileImage/ProfileImage.tsx
  src/components/profile/ActivityDetails.tsx
  src/components/profile/FilteredProductList.tsx
  src/components/profile/ProfileModifyModal.tsx
  src/components/profile/ProfilePageLayout.tsx
  src/components/user/ActivityDetails.tsx
  src/components/user/FilteredProductList.tsx
  src/components/user/FollowUsersModal.tsx
  src/components/user/ProfileCard.tsx
  src/components/user/ProfileModifyModal.tsx
  src/components/user/ProfilePageLayout.tsx
  src/hooks/common/useIntersect.ts
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/pages/profile/[id].tsx
  src/pages/profile/my.tsx
  src/pages/user/[id].tsx
  src/types/product.ts
  src/types/user.ts
Labels: 💡Feature

#143 Feat: 비교하기 모달 띄우는 훅 수정
  src/components/compare/ChangeProductModal.tsx
  src/components/compare/MovingPageModal.tsx
  src/hooks/compare/useCompareModal.tsx
  src/pages/compare/testModal.tsx
Labels: 💡Feature

#151 build: tailwind scrollbar hide 재설치
  package-lock.json
  package.json
Labels: ⚙ Setting

#133 Feat/인증인가 구현
  src/apis/auth/postSignin.ts
  src/apis/auth/postSignup.ts
  src/components/auth/form/AuthFormContainer.tsx
  src/components/auth/form/SignInForm.tsx
  src/components/auth/form/SignupForm.tsx
  src/components/auth/withLogin.tsx
  src/components/common/menu/Header.tsx
  src/hooks/auth/useAuth.ts
  src/pages/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/auth.ts
  src/types/product.ts
Labels: 💡Feature

#156 Feat/Oauth 레이아웃 제작
  src/components/auth/form/OAuthSignupForm.tsx
  src/pages/oauth/signup/[platform].tsx
Labels: 🎨 Style, 😈 BugFix

#153 Feat: 비교하기 페이지 자잘한 css 수정
  src/components/common/menu/Header.tsx
  src/components/common/numberOfCompareProduct/NumberOfCompareProduct.tsx
  src/components/common/productNameTag/ProductNameTag.tsx
  src/components/compare/CompareForm.tsx
  src/components/compare/CompareInput.tsx
  src/pages/compare/index.tsx
Labels: 🎨 Style

#146 feat: 내 정보 수정 모달 남은 요구사항
  src/apis/image.ts
  src/apis/user.ts
  src/components/common/button/BasicButton.tsx
  src/components/common/inputs/AddImageBox.tsx
  src/components/common/modal/ModalWrapper.tsx
  src/components/user/ProfileModifyModal.tsx
  src/types/user.ts
Labels: 💡Feature

#148 feat: 유저 모달 기능
  src/components/user/FollowUsersModal.tsx
  src/hooks/common/useIntersect.ts
Labels: 💡Feature
