Repository 4-2-mogazoa/mogazoa, pull requests merged in 2024-04, with the labels that each got.

#160 Style/유저 페이지 스타일 수정
  src/components/common/activitycard/ActivityCard.tsx
  src/components/common/productcard/ProductCard.tsx
  src/components/user/ActivityDetails.tsx
  src/components/user/ProfileCard.tsx
  src/components/user/ProfilePageLayout.tsx
Labels: 🎨 Style

#155 feat: 상품상세화면 비교하기모달 연결
  src/apis/review.ts
  src/components/productdetail/DetailCard.tsx
  src/components/productdetail/ProductDetail.tsx
  src/components/productdetail/ProductReview.tsx
  src/components/productdetail/ReviewModal.tsx
  src/components/productdetail/ReviewModalAddImageBox.tsx
  src/types/review.ts
Labels: 💡Feature

#140 feat: 비교하기 인풋에서 드롭다운으로 방향키로 이동 가능하도록 구현
  src/components/compare/CompareDropdown.tsx
  src/components/compare/CompareInput.tsx
  src/hooks/compare/useCompareInputState.ts
  src/pages/compare/scrollTest.tsx
Labels: 💡Feature

#145 feat: 모달 내에서 tab으로 포커스 이동
  src/components/common/modal/ModalWrapper.tsx
  src/components/common/modal/MovingPageModal.tsx
  src/components/compare/ChangeProductModal.tsx
  src/utils/trapFocus.ts
Labels: 💡Feature

#154 Fix/헤더검색기능
  src/components/common/menu/Header.tsx
  src/components/home/HomeLayout.tsx
Labels: 💡Feature

#164 Feat:유저 페이지 서버 사이드 렌더링 등
  src/apis/axiosInstance.ts
  src/apis/user.ts
  src/components/user/FilteredProductList.tsx
  src/components/user/FilteredProductListFilter.tsx
  src/components/user/FilteredProductListProducts.tsx
  src/components/user/FollowUsersModal.tsx
  src/components/user/Loading.tsx
  src/components/user/NoProducts.tsx
  src/components/user/ProfileCard.tsx
  src/components/user/ProfilePageLayout.tsx
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/pages/user/[id].tsx
  src/utils/getAccessTokenFromReq.ts
Labels: 💡Feature

#165 feat: 상품상세화면 로그인요청모달연결, 페이지 에러처리 및 기타 오류 수정
  src/components/productdetail/DetailCard.tsx
  src/components/productdetail/MockData.ts
  src/components/productdetail/ProductDetail.tsx
  src/components/productdetail/ProductDetailPageLayout.tsx
  src/components/productdetail/ProductReview.tsx
  src/components/productdetail/ProductStatistics.tsx
  src/components/productdetail/ReviewAlertModal.tsx
  src/components/productdetail/ReviewCard.tsx
  src/components/productdetail/ReviewModal.tsx
  src/components/productdetail/ReviewModalAddImageBox.tsx
  src/hooks/common/useIntersectionObserver.ts
  src/stories/ProductDetailPageLayout.stories.ts
  src/stories/ReviewModalLayout.stories.ts
  src/utils/modalText.ts
Labels: 💡Feature

#169 Feat/Oauth-기능개발
  src/apis/auth/postOAuthSignin.ts
  src/apis/auth/postOAuthSignup.ts
  src/components/auth/OAuthLayout.tsx
  src/components/auth/form/OAuthSignupForm.tsx
  src/components/common/spinner/LodingSpinner.tsx
  src/constants/oauth.ts
  src/hooks/auth/useAuth.ts
  src/pages/oauth/index.tsx
  src/pages/oauth/signup/[platform].tsx
Labels: 💡Feature

#163 Feat/상품추가수정모달 외 잡다한 수정사항들
  src/apis/products.ts
  src/components/common/button/AddProductButton.tsx
  src/components/common/dropdown/product/AddCategoryDropdown.tsx
  src/components/common/dropdown/product/productAutoComplete.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/menu/Header.tsx
  src/components/common/menu/SideBar.tsx
  src/components/common/modal/product/ProductModal.tsx
  src/components/home/HomeLayout.tsx
  src/components/home/ProductList.tsx
  src/components/home/ReviewerRanking.tsx
  src/components/productdetail/DetailCard.tsx
  src/hooks/common/useTrapFocus.ts
  src/types/product.ts
Labels: 💡Feature, 🎨 Style

#173 fix: 빌드 오류 수정
  src/components/productdetail/ReviewCard.tsx
  src/stories/AddImageBox.stories.ts
  src/stories/Header.stories.ts
  src/stories/ProfileImage.stories.ts
  src/stories/SideBar.stories.ts
  src/stories/SingInPage.stories.ts
  src/stories/TextBox.stories.ts
Labels: 😈 BugFix
